// cadastro
POST http://localhost:3001/api/v1/auth/register
Content-Type: application/json

{
    "username": "DemoUser",
    "email": "demo@user.com",
    "password": "demouser1234_"
}

###
// login
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "email": "demo@user.com",
    "password": "demouser1234_"
}

###
// log-out
POST http://localhost:3001/api/v1/auth/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2ZiMzhmYy01MmJmLTQ4MmItOTAyOC02MzY0YzEzMjdjMjMiLCJlbWFpbCI6ImRlbW9AdXNlci5jb20iLCJpYXQiOjE3NzU3MzAyNDgsImV4cCI6MTc3NTczMTE0OH0.TDk06fHxfLGjOz2Kp6KHCbPLAr98LqXoIUIhsTp-FmQ

###
// get me
@token = yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2ZiMzhmYy01MmJmLTQ4MmItOTAyOC02MzY0YzEzMjdjMjMiLCJlbWFpbCI6ImRlbW9AdXNlci5jb20iLCJpYXQiOjE3NzU3MzA3MzYsImV4cCI6MTc3NTczMTYzNn0.9nbyl2DQzU-YbJMScU2CNVnAPq4VSMY4tbhSjC0ml2g
GET http://localhost:3001/api/v1/auth/me
Authorization: Bearer {{token}}

###
// refresh token
POST http://localhost:3001/api/v1/auth/refresh
