### Variáveis de Ambiente
@baseUrl = http://localhost:3001/api/v1
@contentType = application/json

# CRIAR CONTA
# @name register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "username": "tester_resiliente",
    "email": "teste@alpha.com",
    "password": "SenhaSegura123"
}

###

# LOGIN  
# @name login_inicial
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "teste@alpha.com",
    "password": "SenhaSegura123"
}

### 

# EXTRAIR TOKEN DO LOGIN
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NDliNDNjZC0yYWY1LTQ5ZTctOGQ5NC0xYTM4MjY2NjI0YmIiLCJlbWFpbCI6InRlc3RlQGFscGhhLmNvbSIsImlhdCI6MTc3NjI5NTUzNSwiZXhwIjoxNzc2Mjk2NDM1fQ.WmoOq28Lxe6IJeflvPiGVxnSXLl2qKlEPzbsMBtFjeE
@userId = 549b43cd-2af5-49e7-8d94-1a38266624bb

###

# APAGAR CONTA (SOFT DELETE)
DELETE {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}

###

# 5. TENTAR LOGIN COM CONTA APAGADA
# @name login_tentativa_falha
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "teste@alpha.com",
    "password": "SenhaSegura123"
}

###

# 6. RESTAURAR CONTA 
POST {{baseUrl}}/auth/restore
Content-Type: {{contentType}}

{
    "id": "{{userId}}",
    "password": "SenhaSegura123"
}
